### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by chengcheng8632** [wuhy68/Parameter-Efficient-MoE#2]
作者你好，可以给一个训练命令示例吗？是基于deepspeed还是megatron进行训练的？

**Comment by wuhy68** [comment]
训练脚本放在train_scripts/文件夹里，我们暂时还没有实现基于deepspeed还是megatron进行训练的脚本。

**Comment by chengcheng8632** [comment]
好的，感谢回复，请问一下，训练8*34B的模型需要多少显存呀？

**Comment by wuhy68** [comment]
我们会整理好具体的显存需求然后展示出来，目前的实验都是在16xA100上进行的。

**Comment by chengcheng8632** [comment]
好的
