### ISSUE TITLE
Train MOE Error (train_moe.py)

### ISSUE THREAD

**Issue by sahalshajim** [wuhy68/Parameter-Efficient-MoE#3]
Dear @wuhy68 

Thank you for releasing your work to the open-source community.

I was able to fine-tune your `hywu/Camelidae-8x34B` using the `train_qlora.py` script successfully on custom data.
However, the `train_moe.py` gives the following error : 

```
Traceback (most recent call last):
  File "/home/sahal.mullappilly/Parameter-Efficient-MoE/train_moe.py", line 450, in <module>
    train()
  File "/home/sahal.mullappilly/Parameter-Efficient-MoE/train_moe.py", line 398, in train
    nn.init.kaiming_uniform_(p, a=math.sqrt(5))
  File "/home/sahal.mullappilly/miniconda3/envs/camelidae/lib/python3.9/site-packages/torch/nn/init.py", line 412, in kaiming_uniform_
    return tensor.uniform_(-bound, bound)
RuntimeError: "check_uniform_bounds" not implemented for 'Byte'
Traceback (most recent call last):
  File "/home/sahal.mullappilly/Parameter-Efficient-MoE/train_moe.py", line 450, in <module>
    train()
  File "/home/sahal.mullappilly/Parameter-Efficient-MoE/train_moe.py", line 398, in train
    nn.init.kaiming_uniform_(p, a=math.sqrt(5))
  File "/home/sahal.mullappilly/miniconda3/envs/camelidae/lib/python3.9/site-packages/torch/nn/init.py", line 412, in kaiming_uniform_
    return tensor.uniform_(-bound, bound)
RuntimeError: "check_uniform_bounds" not implemented for 'Byte'
```

https://github.com/wuhy68/Parameter-Efficient-MoE/blob/master/train_moe.py#L392
```python
# Zero Init
for n, p in model.named_parameters():
    if "adapter_up" in n:
        nn.init.zeros_(p)
    if "adapter_down" in n:
        nn.init.kaiming_uniform_(p, a=math.sqrt(5))
    if "router" in n:
        try :
            nn.init.kaiming_uniform_(p, a=math.sqrt(5))
        except :
            print(n, type(p))
```
Running this code for debugging gave the following output : `base_model.model.model.layers.0.mlp.moe_adapter.router.weight <class 'bitsandbytes.nn.modules.Params4bit'>`

Please advice as to how I can resolve this issue. Thanks

**Comment by wuhy68** [comment]
You have to avoid converting the MOE adapter into <bitsandbytes.nn.modules.Params4bit>. I have reimplemented the "_load_pretrained_model" function in transformers_utils.py. I hope this can help you.

**Comment by sahalshajim** [comment]
Hi @wuhy68, thank you for your response. However the issue still persists.

I believe the "_load_pretrained_model" function in transformers_utils.py is utilized as shown in this line
https://github.com/wuhy68/Parameter-Efficient-MoE/blob/master/train_moe.py#L54

I have verified this in debugging as well that your custom "_load_pretrained_model" is used for loading the model.
In fact I have not changed the code in anyway. I have only changed the dataset and gave the pretrained checkpoint as `pretrained_path=hywu/Camelidae-8x34B`,

Please advice as to what steps can I try now.

**Comment by wuhy68** [comment]
I think you can try transformers==4.34.0.dev0, this is the transformers version I used. I have updated the requirements.txt for reference.

**Comment by sahalshajim** [comment]
Hi @wuhy68, Thank you for updating the `requirements.txt` file. Now I'm able to successfully load and train the model.
