### ISSUE TITLE
When will the training data and the evaluation scripts be released?

### ISSUE THREAD

**Issue by jiangwangyi** [wuhy68/Parameter-Efficient-MoE#4]

**Comment by wuhy68** [comment]
The training data construction has been illustrated in our paper. As for the evaluation process, we utilize opencompass and lm_eval to evaluate our model, you can directly load our models and utilize these repos for evaluation.

**Comment by jiangwangyi** [comment]
Without the `filtration and sampling` script, we cannot get exactly the same dataset as what `Camelidae` is trained on.

**Comment by wuhy68** [comment]
We will incorporate the open-source dataset into our plans.

**Comment by monster119120** [comment]
同求，辛苦作者大大
