### ISSUE TITLE
关于训练脚本的问题

### ISSUE THREAD

**Issue by Yu-Yang-Li** [wuhy68/Parameter-Efficient-MoE#5]
感谢分享，很有启发性的工作！
有一个问题想向您请教：

请问脚本中pretrained_path= ，填写的是LLAMA/Yi模型[01-ai/Yi-34B-Chat]的路径，实现的是通过训练产生MOE模型吗？
还是填写例如hywu/Camelidae-8x34B已经构造的MOE模型，通过全量（train_moe）或Qlora（train_qlora）来实现对已有模型的微调？

感谢百忙中抽出时间解惑

**Comment by wuhy68** [comment]
训练脚本pretrained_path填的是dense模型（01-ai/Yi-34B）的路径，实现通过训练产生MoE模型。

**Comment by Yu-Yang-Li** [comment]
感谢！
